using Dungnz.Engine; using Dungnz.Engine.Commands; using Dungnz.Models; using Dungnz.Systems; using Dungnz.Tests.Helpers; using FluentAssertions; using Microsoft.Extensions.Logging; using Moq; using Xunit;
namespace Dungnz.Tests;
public class CommandHandlerShowRoomTests {
    private static CommandContext MakeContext(Player? player = null, Room? room = null, FakeDisplayService? display = null) {
        var p = player ?? new Player { Name = "Tester", HP = 100, MaxHP = 100, Attack = 10, Defense = 5 };
        var r = room ?? new Room { Description = "A dusty room." }; var d = display ?? new FakeDisplayService();
        return new CommandContext { Player = p, CurrentRoom = r, Rng = new Random(42), Stats = new RunStats(), SessionStats = new SessionStats(), RunStart = DateTime.UtcNow, Display = d, Combat = new Mock<ICombatEngine>().Object, Equipment = new EquipmentManager(d), InventoryManager = new InventoryManager(d), Narration = new NarrationService(new Random(42)), Achievements = new AchievementSystem(), AllItems = new List<Item>(), Difficulty = DifficultySettings.For(Difficulty.Normal), DifficultyLevel = Difficulty.Normal, Logger = new Mock<ILogger>().Object, Events = new GameEvents(), CurrentFloor = 1, TurnConsumed = true, GameOver = false, ExitRun = _ => { }, RecordRunEnd = (_, _) => { }, GetCurrentlyEquippedForItem = (_, _) => null, GetDifficultyName = () => "Normal", HandleShrine = () => { }, HandleContestedArmory = () => { }, HandlePetrifiedLibrary = () => { }, HandleTrapRoom = () => { } };
    }
    [Fact] public void MoveCommand_SuccessfulMove_CallsShowRoomOnce() { var display = new FakeDisplayService(); var roomA = new Room { Description = "Room A" }; var roomB = new Room { Description = "Room B" }; roomA.Exits[Direction.North] = roomB; var ctx = MakeContext(room: roomA, display: display); var handler = new GoCommandHandler(); var initialShowRoomCount = display.ShowRoomCallCount; handler.Handle("north", ctx); display.ShowRoomCallCount.Should().Be(initialShowRoomCount + 1); }
    [Fact] public void TakeCommand_SingleItem_CallsShowRoomOnce() { var display = new FakeDisplayService(); var player = new Player { Name = "Tester", HP = 100, MaxHP = 100 }; var room = new Room { Description = "A room with loot" }; var sword = new Item { Name = "Iron Sword", Type = ItemType.Weapon, AttackBonus = 5 }; room.AddItem(sword); var ctx = MakeContext(player: player, room: room, display: display); var handler = new TakeCommandHandler(); var initialShowRoomCount = display.ShowRoomCallCount; handler.Handle("sword", ctx); display.ShowRoomCallCount.Should().Be(initialShowRoomCount + 1); }
    [Fact] public void TakeCommand_CancelMenu_CallsShowRoomOnce() { var display = new FakeDisplayService(); var player = new Player { Name = "Tester", HP = 100, MaxHP = 100 }; var room = new Room { Description = "A room with loot" }; var sword = new Item { Name = "Iron Sword", Type = ItemType.Weapon }; room.AddItem(sword); var ctx = MakeContext(player: player, room: room, display: display); var handler = new TakeCommandHandler(); var initialShowRoomCount = display.ShowRoomCallCount; handler.Handle(string.Empty, ctx); display.ShowRoomCallCount.Should().Be(initialShowRoomCount + 1); }
    [Fact] public void UseCommand_WithDirectItemName_CallsShowRoomOnce() { var display = new FakeDisplayService(); var player = new Player { Name = "Tester", HP = 50, MaxHP = 100 }; var potion = new Item { Name = "Health Potion", Type = ItemType.Consumable, HealAmount = 20 }; player.Inventory.Add(potion); var ctx = MakeContext(player: player, display: display); var handler = new UseCommandHandler(); var initialShowRoomCount = display.ShowRoomCallCount; handler.Handle("Health Potion", ctx); display.ShowRoomCallCount.Should().Be(initialShowRoomCount + 1); }
    [Fact] public void ExamineCommand_ItemFound_CallsShowRoomOnce() { var display = new FakeDisplayService(); var player = new Player { Name = "Tester", HP = 100, MaxHP = 100 }; var sword = new Item { Name = "Iron Sword", Type = ItemType.Weapon, Description = "A sturdy blade" }; player.Inventory.Add(sword); var ctx = MakeContext(player: player, display: display); var handler = new ExamineCommandHandler(); var initialShowRoomCount = display.ShowRoomCallCount; handler.Handle("sword", ctx); display.ShowRoomCallCount.Should().Be(initialShowRoomCount + 1); }
    [Fact] public void CraftCommand_WithRecipeName_CallsShowRoomOnce() { var display = new FakeDisplayService(); var player = new Player { Name = "Tester", HP = 100, MaxHP = 100 }; var ctx = MakeContext(player: player, display: display); var handler = new CraftCommandHandler(); var initialShowRoomCount = display.ShowRoomCallCount; handler.Handle("NonExistentRecipe", ctx); display.ShowRoomCallCount.Should().Be(initialShowRoomCount + 1); }
    [Fact] public void CraftCommand_CancelMenu_CallsShowRoomOnce() { var display = new FakeDisplayService(); var player = new Player { Name = "Tester", HP = 100, MaxHP = 100 }; var ctx = MakeContext(player: player, display: display); var handler = new CraftCommandHandler(); var initialShowRoomCount = display.ShowRoomCallCount; handler.Handle(string.Empty, ctx); display.ShowRoomCallCount.Should().Be(initialShowRoomCount + 1); }
    [Fact] public void CompareCommand_WithItemName_CallsShowRoomOnce() { var display = new FakeDisplayService(); var player = new Player { Name = "Tester", HP = 100, MaxHP = 100 }; var sword = new Item { Name = "Iron Sword", Type = ItemType.Weapon, IsEquippable = true }; player.Inventory.Add(sword); var ctx = MakeContext(player: player, display: display); var handler = new CompareCommandHandler(); var initialShowRoomCount = display.ShowRoomCallCount; handler.Handle("Iron Sword", ctx); display.ShowRoomCallCount.Should().Be(initialShowRoomCount, "ShowRoom should NOT be called after comparison so it stays visible (Issue #1314)"); }
}
