using Dungnz.Models; using Dungnz.Systems; using Dungnz.Systems.Enemies; using FluentAssertions; using Xunit;
namespace Dungnz.Tests;
[Collection("save-system")]
public class EnemySaveLoadTests : IDisposable {
    private readonly string _saveDir;
    public EnemySaveLoadTests() { _saveDir = Path.Combine(Path.GetTempPath(), $"dungnz_enemy_save_test_{Guid.NewGuid()}"); SaveSystem.OverrideSaveDirectory(_saveDir); }
    public void Dispose() { if (Directory.Exists(_saveDir)) Directory.Delete(_saveDir, recursive: true); }
    [Fact] public void RoundTrip_MultipleEnemyTypes_PreservesAllProperties() { var player = new Player { Name = "Tester", HP = 100, MaxHP = 100 }; var room1 = new Room { Description = "Goblin Room" }; var goblin = new Goblin(); goblin.HP = 15; goblin.Name = "Sneaky Goblin"; room1.Enemy = goblin; var room2 = new Room { Description = "Troll Cave" }; var troll = new Troll(); troll.HP = 45; troll.Name = "Mountain Troll"; room2.Enemy = troll; var room3 = new Room { Description = "Knight's Chamber" }; var darkKnight = new DarkKnight(); darkKnight.HP = 30; darkKnight.Name = "Corrupted Knight"; darkKnight.IsElite = true; room3.Enemy = darkKnight; room1.Exits[Direction.North] = room2; room2.Exits[Direction.South] = room1; room2.Exits[Direction.East] = room3; room3.Exits[Direction.West] = room2; var state = new GameState(player, room1); SaveSystem.SaveGame(state, "multi_enemy"); var loaded = SaveSystem.LoadGame("multi_enemy"); var loadedRoom1 = loaded.CurrentRoom; loadedRoom1.Enemy.Should().NotBeNull(); loadedRoom1.Enemy.Should().BeOfType<Goblin>(); loadedRoom1.Enemy!.HP.Should().Be(15); loadedRoom1.Enemy.Name.Should().Be("Sneaky Goblin"); var loadedRoom2 = loadedRoom1.Exits[Direction.North]; loadedRoom2.Enemy.Should().NotBeNull(); loadedRoom2.Enemy.Should().BeOfType<Troll>(); loadedRoom2.Enemy!.HP.Should().Be(45); loadedRoom2.Enemy.Name.Should().Be("Mountain Troll"); var loadedRoom3 = loadedRoom2.Exits[Direction.East]; loadedRoom3.Enemy.Should().NotBeNull(); loadedRoom3.Enemy.Should().BeOfType<DarkKnight>(); loadedRoom3.Enemy!.HP.Should().Be(30); loadedRoom3.Enemy.Name.Should().Be("Corrupted Knight"); loadedRoom3.Enemy.IsElite.Should().BeTrue(); }
    [Fact] public void RoundTrip_EnemyWithStatusEffects_PreservesEffects() { var player = new Player { Name = "Tester", HP = 100, MaxHP = 100 }; var room = new Room { Description = "Poisoned Enemy Room" }; var goblin = new Goblin(); goblin.HP = 10; goblin.IsAmbush = true; room.Enemy = goblin; var state = new GameState(player, room); SaveSystem.SaveGame(state, "enemy_flags"); var loaded = SaveSystem.LoadGame("enemy_flags"); loaded.CurrentRoom.Enemy.Should().NotBeNull(); loaded.CurrentRoom.Enemy!.IsAmbush.Should().BeTrue(); loaded.CurrentRoom.Enemy.HP.Should().Be(10); }
    [Fact] public void RoundTrip_EnemyWithSpecialMechanics_PreservesAIState() { var player = new Player { Name = "Tester", HP = 100, MaxHP = 100 }; var room = new Room { Description = "Boss Room", IsExit = true }; var boss = new DungeonBoss(); boss.HP = 40; boss.IsEnraged = true; boss.IsCharging = true; boss.ChargeActive = false; room.Enemy = boss; var state = new GameState(player, room); SaveSystem.SaveGame(state, "boss_ai_state"); var loaded = SaveSystem.LoadGame("boss_ai_state"); var loadedBoss = loaded.CurrentRoom.Enemy as DungeonBoss; loadedBoss.Should().NotBeNull(); loadedBoss!.HP.Should().Be(40); loadedBoss.IsEnraged.Should().BeTrue(); loadedBoss.IsCharging.Should().BeTrue(); loadedBoss.ChargeActive.Should().BeFalse(); }
    [Fact] public void RoundTrip_MultipleRoomsWithAndWithoutEnemies_PreservesCorrectly() { var player = new Player { Name = "Tester", HP = 100, MaxHP = 100 }; var room1 = new Room { Description = "Empty Start Room" }; var room2 = new Room { Description = "Goblin Room" }; var goblin = new Goblin(); goblin.HP = 20; room2.Enemy = goblin; var room3 = new Room { Description = "Cleared Room", Looted = true }; var room4 = new Room { Description = "Troll Room" }; var troll = new Troll(); troll.HP = 60; room4.Enemy = troll; room1.Exits[Direction.North] = room2; room2.Exits[Direction.South] = room1; room2.Exits[Direction.East] = room3; room3.Exits[Direction.West] = room2; room3.Exits[Direction.North] = room4; room4.Exits[Direction.South] = room3; var state = new GameState(player, room1); SaveSystem.SaveGame(state, "mixed_rooms"); var loaded = SaveSystem.LoadGame("mixed_rooms"); var loadedRoom1 = loaded.CurrentRoom; loadedRoom1.Enemy.Should().BeNull("start room has no enemy"); var loadedRoom2 = loadedRoom1.Exits[Direction.North]; loadedRoom2.Enemy.Should().NotBeNull("goblin room has enemy"); loadedRoom2.Enemy.Should().BeOfType<Goblin>(); var loadedRoom3 = loadedRoom2.Exits[Direction.East]; loadedRoom3.Enemy.Should().BeNull("cleared room has no enemy"); loadedRoom3.Looted.Should().BeTrue(); var loadedRoom4 = loadedRoom3.Exits[Direction.North]; loadedRoom4.Enemy.Should().NotBeNull("troll room has enemy"); loadedRoom4.Enemy.Should().BeOfType<Troll>(); }
    [Fact] public void RoundTrip_EnemyWithCustomStats_PreservesExactValues() { var player = new Player { Name = "Tester", HP = 100, MaxHP = 100 }; var room = new Room { Description = "Custom Enemy Room" }; var darkKnight = new DarkKnight(); darkKnight.HP = 23; darkKnight.MaxHP = 50; darkKnight.Attack = 25; darkKnight.Defense = 15; darkKnight.XPValue = 100; darkKnight.IsElite = true; darkKnight.IsUndead = false; room.Enemy = darkKnight; var state = new GameState(player, room); SaveSystem.SaveGame(state, "custom_stats"); var loaded = SaveSystem.LoadGame("custom_stats"); var loadedEnemy = loaded.CurrentRoom.Enemy as DarkKnight; loadedEnemy.Should().NotBeNull(); loadedEnemy!.HP.Should().Be(23); loadedEnemy.MaxHP.Should().Be(50); loadedEnemy.Attack.Should().Be(25); loadedEnemy.Defense.Should().Be(15); loadedEnemy.XPValue.Should().Be(100); loadedEnemy.IsElite.Should().BeTrue(); loadedEnemy.IsUndead.Should().BeFalse(); }
    [Fact] public void RoundTrip_DeadEnemy_MarkedCorrectly() { var player = new Player { Name = "Tester", HP = 100, MaxHP = 100 }; var room = new Room { Description = "Cleared Combat Room" }; var goblin = new Goblin(); goblin.HP = 0; room.Enemy = goblin; var state = new GameState(player, room); SaveSystem.SaveGame(state, "dead_enemy"); var loaded = SaveSystem.LoadGame("dead_enemy"); loaded.CurrentRoom.Enemy.Should().NotBeNull(); loaded.CurrentRoom.Enemy!.HP.Should().Be(0); loaded.CurrentRoom.Enemy.IsDead.Should().BeTrue(); }
}
